markdown: GFM
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: "Meshtastic Ярославль"
description: "Инструкция по настройке и использованию meshtastic в Ярославле"
show_downloads: false
